### ISSUE TITLE
Proposal for the definition of production machine learning

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#392] opened 2023-03-07 05:51 UTC
I think it is better to know what production machine learning really means in the context.

**Comment by axsaucedo** [comment] 2023-03-07 06:00
Hi @zhimin-z, following up from the discussion on #366 wanted to provide further comments and closing this issue as we won't realistically be able to come up with a perfect definition and heuristic that will result in non-biased / non-subjective opinions.

Unfortunately when it comes to maintenance of OSS libraries there needs to be an ultimate decision that needs to be made, we can end up discussing forever but when it comes to adding 1-2 lines we can't have endless discussions. The end decisions won't be perfect, and there will be ambiguity as we won't reach terminology that will be exact without overlap, and there will also be subjectivity as this list is maintained by humans.

However we can't be discussing forever and a decision has to be made, unfortunately if a tool is being added or pushed back on, people may agree or disagree but we'll have to commit and move forward - I am aware you can't keep everyone happy but that's what happens in larger projects.

This is to manage expectations as we could try to put together a definition of "production ML" in the contribute and that will still not provide the full non-overlapping clarity.

Because of this I want to manage expectations as there will be future decisions in this and many other projects that may not be perfect but that need to be made in order to progress.

Based on this I will close this issue so we don't end up pursuing something that realistically won't provide a silver-bullet for all and every decision, as there will be further disappointment when realising there will still be a human making the decision on whether things get added or removed, as opposed to a rule based algorithm.

**Closed by axsaucedo** 2023-03-07 06:00 UTC

**Comment by zhimin-z** [comment] 2023-03-07 06:07
But I think it is better under what production ML means in your mind, currently, I found myself very frustrated about the transparency and if this continues, I have to get out. @axsaucedo I really need an explanation of what it means by "production machine learning"

**Comment by axsaucedo** [comment] 2023-03-07 06:19
> But I think it is better under what production ML means in your mind, currently, I found myself very frustrated about the transparency and if this continues, I have to opt out of this project.

That's absolutely your right @zhimin-z , you are a volunteer and your work is very much appreciated but you are not forced to contribute - projects will have different approaches to accepting or rejecting changes, so you can definitely feel free to contribute that makes you feel fulfilled / excited in the interactions and process.

From a transparency standpoint I completely disagree, as I aim to be transparent with the reasoning - what you ask for is a non-realistic "definition of production ML that will suddenly remove the ambiguity", however from a transparency standpoint I can confirm that I verbalise my thinking around the issues as well as *my opinions* which result in the decisions.

Are my opinions 100% correct? Definitely not. 

Are they subjective? Absolutely, I am indeed a human with strong opinions. 

Will we end up in a situation where everyone is happy and agrees with the decisions? Most definitely not in a project of this size.

I want to manage expectations as although I do very much appreciate the contributions, as I mentioned above we won't end up in a situation where we get things merged through "victory of exhaustion from discussion", especially not when a PR with 3 lines has a 100 line discussion to remove 2 out of those 3 lines.

I want to really emphasise that your efforts are appreciated, and I do also know they come from the best place as they try to make this list better and contribute to the MLOps ecosystem - my actions also aim to come from a good place and with the limited time to make decisions some may come as incorrect or unfair but as mentioned above, in order to move forward we'll have to disagree and commit, and the person that makes the decision will have to do so even if not everyone is happy.

**Comment by zhimin-z** [comment] 2023-03-07 06:27
> > But I think it is better under what production ML means in your mind, currently, I found myself very frustrated about the transparency and if this continues, I have to opt out of this project.
> 
> That's absolutely your right @zhimin-z , you are a volunteer and your work is very much appreciated but you are not forced to contribute - projects will have different approaches to accepting or rejecting changes, so you can definitely feel free to contribute to other projects instead that makes you feel fulfilled / excited in the interactions and process.
> 
> From a transparency standpoint I completely disagree, as I aim to be transparent with the reasoning - what you ask for is a non-realistic "definition of production ML that will suddenly remove the ambiguity", however from a transparency standpoint I can confirm that I verbalise my thinking around the issues as well as _my opinions_ which result in the decisions.
> 
> Are my opinions 100% correct? Definitely not.
> 
> Are they subjective? Absolutely, I am indeed a human with strong opinions.
> 
> Will we end up in a situation where everyone is happy and agrees with the decisions? Most definitely not in a project of this size.
> 
> I want to manage expectations as although I do very much appreciate the contributions, as I mentioned above we won't end up in a situation where we get things merged through "victory of exhaustion from discussion", especially not when a PR with 3 lines has a 100 line discussion to remove 2 out of those 3 lines.
> 
> I want to really emphasise that your efforts are appreciated, and I do also know they come from the best place as they try to make this list better and contribute to the MLOps ecosystem - my actions also aim to come from a good place and with the limited time to make decisions some may come as incorrect or unfair but as mentioned above, in order to move forward we'll have to disagree and commit, and the person that makes the decision will have to do so even if not everyone is happy.

But the current scenario is that you are the owner of the project that I barely have any right to argue with you over the controversy. This is not a healthy atmosphere since we cannot make the best list without rounds of discussion (discussion is needed for a better understanding of the key issues). My issues/PRs only get closed without me understanding the underlying reasons fully since the current guideline is very vague and ambiguous. @axsaucedo I do think we need a better plan for healthy and transparent guideline for commitment.

**Comment by zhimin-z** [comment] 2023-03-07 07:19
> > But I think it is better under what production ML means in your mind, currently, I found myself very frustrated about the transparency and if this continues, I have to opt out of this project.
> 
> That's absolutely your right @zhimin-z , you are a volunteer and your work is very much appreciated but you are not forced to contribute - projects will have different approaches to accepting or rejecting changes, so you can definitely feel free to contribute to other projects instead that makes you feel fulfilled / excited in the interactions and process, as well as more aligned with your principles / ways of seeing things.
> 
> From a transparency standpoint I completely disagree, as I aim to be transparent with the reasoning - what you ask for is a non-realistic "definition of production ML that will suddenly remove the ambiguity", however from a transparency standpoint I can confirm that I verbalise my thinking around the issues as well as _my opinions_ which result in the decisions.
> 
> Are my opinions 100% correct? Definitely not.
> 
> Are they subjective? Absolutely, I am indeed a human with strong opinions.
> 
> Will we end up in a situation where everyone is happy and agrees with the decisions? Most definitely not in a project of this size.
> 
> I want to manage expectations as although I do very much appreciate the contributions, however as I mentioned above we can't have situations where we get things merged through "victory of exhaustion from discussion", especially not when a PR with 3 lines has a 100 line discussion to remove 2 out of those 3 lines.
> 
> I want to really emphasise that your efforts are appreciated, and I do also know they come from the best place as they try to make this list better and contribute to the MLOps ecosystem - my actions also aim to come from a good place and with the limited time to make decisions some may come as incorrect or unfair but as mentioned above, in order to move forward we'll have to disagree and commit, and the person that makes the decision will have to do so even if not everyone is happy.

I agree that there exists no way to make everyone happy, but the current standard is so blurred that I am always falling into the same scenario again and again, but still have not fully understood why I was wrong in terms of the current contribution guideline. @axsaucedo I hope OSS contributors can have more transparency and they do not follow the Sisyphus discussion without a lot of time wasting. @axsaucedo

**Comment by zhimin-z** [comment] 2023-03-07 08:30
> > But I think it is better under what production ML means in your mind, currently, I found myself very frustrated about the transparency and if this continues, I have to opt out of this project.
> 
> That's absolutely your right @zhimin-z , you are a volunteer and your work is very much appreciated but you are not forced to contribute - projects will have different approaches to accepting or rejecting changes, so you can definitely feel free to contribute to other projects instead that makes you feel fulfilled / excited in the interactions and process.
> 
> From a transparency standpoint I completely disagree, as I aim to be transparent with the reasoning - what you ask for is a non-realistic "definition of production ML that will suddenly remove the ambiguity", however from a transparency standpoint I can confirm that I verbalise my thinking around the issues as well as _my opinions_ which result in the decisions.
> 
> Are my opinions 100% correct? Definitely not.
> 
> Are they subjective? Absolutely, I am indeed a human with strong opinions.
> 
> Will we end up in a situation where everyone is happy and agrees with the decisions? Most definitely not in a project of this size.
> 
> I want to manage expectations as although I do very much appreciate the contributions, as I mentioned above we won't end up in a situation where we get things merged through "victory of exhaustion from discussion", especially not when a PR with 3 lines has a 100 line discussion to remove 2 out of those 3 lines.
> 
> I want to really emphasise that your efforts are appreciated, and I do also know they come from the best place as they try to make this list better and contribute to the MLOps ecosystem - my actions also aim to come from a good place and with the limited time to make decisions some may come as incorrect or unfair but as mentioned above, in order to move forward we'll have to disagree and commit, and the person that makes the decision will have to do so even if not everyone is happy.

But the current scenario is that you are the owner of the project that we barely have any room to negotiate with you over the controversy. This is not a healthy atmosphere since we cannot make a better MLOps list without rounds of discussion (discussion is needed for a better understanding of the key issues and proposal of feasible resolutions). My issues/PRs often get closed without me understanding the underlying reasons fully since the current guideline is very vague and ambiguous and I cannot realize why I am wrong. @axsaucedo I do think we need a better plan for a healthy and transparent guideline for commitment.

**Comment by zhimin-z** [comment] 2023-03-08 16:35
> > But I think it is better under what production ML means in your mind, currently, I found myself very frustrated about the transparency and if this continues, I have to opt out of this project.
> 
> That's absolutely your right @zhimin-z , you are a volunteer and your work is very much appreciated but you are not forced to contribute - projects will have different approaches to accepting or rejecting changes, so you can definitely feel free to contribute to other projects instead that makes you feel fulfilled / excited in the interactions and process, as well as more aligned with your principles / ways of seeing things.
> 
> From a transparency standpoint I completely disagree, as I aim to be transparent with the reasoning - what you ask for is a non-realistic "definition of production ML that will suddenly remove the ambiguity", however from a transparency standpoint I can confirm that I verbalise my thinking around the issues as well as _my opinions_ which result in the decisions.
> 
> Are my opinions 100% correct? Definitely not.
> 
> Are they subjective? Absolutely, I am indeed a human with strong opinions.
> 
> Will we end up in a situation where everyone is happy and agrees with the decisions? Most definitely not in a project of this size.
> 
> I want to manage expectations as although I do very much appreciate the contributions, however as I mentioned above we can't have situations where we get things merged through "victory of exhaustion from discussion", especially not when a PR with 3 lines has a 100 line discussion to remove 2 out of those 3 lines.
> 
> I want to really emphasise that your efforts are appreciated, and I do also know they come from the best place as they try to make this list better and contribute to the MLOps ecosystem - my actions also aim to come from a good place and with the limited time to make decisions some may come as incorrect or unfair but as mentioned above, in order to move forward we'll have to disagree and commit, and the person that makes the decision will have to do so even if not everyone is happy.

I agree that there exists no way to make everyone happy, but the current standard is so blurred and you are the only person that understands it well. Since I have no idea what's on your mind, I always fall into the same PR closed scenario again and again and still have no idea why I was wrong in terms of the current contribution guideline. I hope OSS contributors can have more transparency and they do not have to speculate your merge criteria. Why not build up a clear guideline so we both eliminate the Sisyphus discussion appearing in every PR? @axsaucedo

**Comment by axsaucedo** [comment] 2023-03-08 17:37
This is going in circles again, and this point just doesn't seem get across as the exact same issue of going in never-ending discusison is happening here. As mentioned already, I do see the idea of prod ML definition as useful but it won't solve these issues of never-ending discussions as there will always be ambiguity, especially in a field as fast-growing as prod ML.

I have updated the [CONTRIBUTING.md](https://github.com/EthicalML/awesome-production-machine-learning/blob/master/CONTRIBUTING.md) to make it clear that the principle of "disagree and commit" will be used to review PRs/issues which will be closed if they go in endless back-and-forths. 

In the many years maintaining open source projects I've rarely had clashing interactions like these, which are not healthy this or any project. I haven't had to do this in the past, but given the context moving forward it will be a requirement to align these decision-making principles, or as mentioned above I wish you best contributing to other projects instead of this one. 

Thank you.

**Comment by zhimin-z** [comment] 2023-03-08 17:49
> This is going in circles again, and this point just doesn't seem get across as the exact same issue of going in never-ending discusison is happening here. As mentioned already, I do see the idea of prod ML definition as useful but it won't solve these issues of never-ending discussions as there will always be ambiguity, especially in a field as fast-growing as prod ML.
> 
> I have updated the [CONTRIBUTING.md](https://github.com/EthicalML/awesome-production-machine-learning/blob/master/CONTRIBUTING.md) to make it clear that the principle of "disagree and commit" will be used to review PRs/issues which will be closed if they go in endless back-and-forths.
> 
> In the many years maintaining open source projects I've rarely had clashing interactions like these, which are not healthy this or any project. I haven't had to do this in the past, but given the context moving forward it will be a requirement to align these decision-making principles, or as mentioned above I wish you best contributing to other projects instead of this one.
> 
> Thank you.

I do not see anything enlightening in the contribution file update. What does it mean by "3 line PRs resulting in 100 line discussion"? Do I expect we are discussing one question again and again? The core issue is that the current guideline is so blurring that the contributor cannot understand it well, thus resulting in the fact they seldom understand what're the criteria in your mind. @axsaucedo

**Comment by zhimin-z** [comment] 2023-03-08 17:54
"As mentioned already, I do see the idea of prod ML definition as useful but it won't solve these issues of never-ending discussions as there will always be ambiguity, especially in a field as fast-growing as prod ML."

We can tweak the criteria timely as the AI landscape evolves, this would definitely help to avoid discussion detours. If there is no clear guideline and our contribution gets closed without any good reason, then the whole project would eventually lose its vitality and soon become outpaced in OSS community. @axsaucedo
